export interface userActionType {
	[key: string]: { shortDescription: string; command: string; description: string; args?: any }
}
const UserActions: userActionType = {
	Pin: { description: 'User Action: pin', shortDescription: 'Pin', command: '/pin' },
	AddPin: { description: 'User Action: Add Pin', shortDescription: 'AddPin', command: '/addPin' },
	Unpin: { description: 'User Action: Unpin', shortDescription: 'Unpin', command: '/unPin' },
	ClearPins: { description: 'User Action: Clear Pins', shortDescription: 'ClearPins', command: '/clearPin' },
	TogglePin: { description: 'User Action: TogglePin', shortDescription: 'TogglePin', command: '/togglePin' },
	PinScreen2: { description: 'User Action: Pin Screen2', shortDescription: 'PinScreen2', command: '/pin2' },
	UnpinScreen2: { description: 'User Action: Unpin Screen2', shortDescription: 'UnpinScreen2', command: '/unPin2' },
	ClearPinsScreen2: {
		description: 'User Action: Clear PinsScreen2',
		shortDescription: 'ClearPinsScreen2',
		command: '/clearPin2',
	},
	TogglePinScreen2: {
		description: 'User Action: Toggle PinScreen2',
		shortDescription: 'TogglePinScreen2',
		command: '/togglePin2',
	},
	RemotePin: { description: 'User Action: Remote Pin', shortDescription: 'RemotePin', command: '/remotePin' },
	RemoteAddPin: {
		description: 'User Action: Remote AddPin',
		shortDescription: 'RemoteAddPin',
		command: '/remoteAddPin',
	},
	RemoteUnpin: { description: 'User Action: Remote Unpin', shortDescription: 'RemoteUnpin', command: '/remoteUnPin' },
	RemoteClearPin: {
		description: 'User Action: Remote ClearPin',
		shortDescription: 'RemoteClearPin',
		command: '/remoteClearPin',
	},
	RemoteTogglePin: {
		description: 'User Action: Remote TogglePin',
		shortDescription: 'RemoteTogglePin',
		command: '/remoteTogglePin',
	},
	RemotePinScreen2: {
		description: 'User Action: Remote Pin Screen2',
		shortDescription: 'RemotePinScreen2',
		command: '/remotePin2',
	},
	RemoteUnpinScreen2: {
		description: 'User Action: Remote Unpin Screen2',
		shortDescription: 'RemoteUnpinScreen2',
		command: '/remoteUnPin2',
	},
	RemoteClearPinScreen2: {
		description: 'User Action: Remote Clear PinScreen2',
		shortDescription: 'RemoteClearPinScreen2',
		command: '/remoteClearPin2',
	},
	RemoteTogglePinScreen2: {
		description: 'User Action: Remote Toggle Pin Screen2',
		shortDescription: 'RemoteTogglePinScreen2',
		command: '/remoteTogglePin2',
	},
	Spotlight: { description: 'User Action: Spotlight', shortDescription: 'Spotlight', command: '/spot' },
	AddSpotlight: { description: 'User Action: Add Spotlight', shortDescription: 'AddSpotlight', command: '/addSpot' },
	UnSpotlight: { description: 'User Action: Un Spotlight', shortDescription: 'UnSpotlight', command: '/unSpot' },
	ToggleSpotlight: {
		description: 'User Action: Toggle Spotlight',
		shortDescription: 'ToggleSpotlight',
		command: '/toggleSpot',
	},
	TurnVideoOn: { description: 'User Action: Turn Video On', shortDescription: 'TurnVideoOn', command: '/videoOn' },
	TurnVideoOff: { description: 'User Action: Turn Video Off', shortDescription: 'TurnVideoOff', command: '/videoOff' },
	ToggleVideoState: {
		description: 'User Action: Toggle Video State',
		shortDescription: 'ToggleVideoState',
		command: '/toggleVideo',
	},
	Mute: { description: 'User Action: Mute', shortDescription: 'Mute', command: '/mute' },
	Unmute: { description: 'User Action: Unmute', shortDescription: 'Unmute', command: '/unMute' },
	ToggleMuteState: {
		description: 'User Action: ToggleMuteState',
		shortDescription: 'ToggleMuteState',
		command: '/toggleMute',
	},
	SendAChatViaDM: { description: 'User Action: SendAChatViaDM', shortDescription: 'SendAChatViaDM', command: '/chat' },
	RemoteChat: { description: 'User Action: RemoteChat', shortDescription: 'RemoteChat', command: '/remoteChat' },
	RaiseHand: { description: 'User Action: RaiseHand', shortDescription: 'RaiseHand', command: '/raiseHand' },
	LowerHand: { description: 'User Action: LowerHand', shortDescription: 'LowerHand', command: '/lowerHand' },
	ToggleHand: { description: 'User Action: ToggleHand', shortDescription: 'ToggleHand', command: '/toggleHand' },
	Rename: { description: 'User Action: Rename', shortDescription: 'Rename', command: '/rename' },
	MakeHost: { description: 'User Action: MakeHost', shortDescription: 'MakeHost', command: '/makeHost' },
	MakeCoHost: { description: 'User Action: MakeCoHost', shortDescription: 'MakeCoHost', command: '/makeCoHost' },
	RevokeCoHost: {
		description: 'User Action: RevokeCoHost',
		shortDescription: 'RevokeCoHost',
		command: '/revokeCoHost',
	},
	ReclaimHost: { description: 'User Action: ReclaimHost', shortDescription: 'ReclaimHost', command: '/reclaimHost' },
	MakePanelist: {
		description: 'User Action: MakePanelist',
		shortDescription: 'MakePanelist',
		command: '/makePanelist',
	},
	MakeAttendee: {
		description: 'User Action: MakeAttendee',
		shortDescription: 'MakeAttendee',
		command: '/makeAttendee',
	},
	EjectParticipant: {
		description: 'User Action: EjectParticipant',
		shortDescription: 'EjectParticipant',
		command: '/eject',
	},
	SendParticipantToBreakoutRoom: {
		description: 'User Action: SendParticipantToBreakoutRoom',
		shortDescription: 'SendParticipantToBreakoutRoom',
		command: '/sendToBreakout',
	},
	RemoveParticipantFromBreakoutRoom: {
		description: 'User Action: RemoveParticipantFromBreakoutRoom',
		shortDescription: 'RemoveParticipantFromBreakoutRoom',
		command: '/removeFromBreakout',
	},
	AssignParticipantToBreakoutRoom: {
		description: 'User Action: AssignParticipantToBreakoutRoom',
		shortDescription: 'AssignParticipantToBreakoutRoom',
		command: '/assignToBreakout',
	},
	UnassignParticipantFromBreakoutRoom: {
		description: 'User Action: UnassignParticipantFromBreakoutRoom',
		shortDescription: 'UnassignParticipantFromBreakoutRoom',
		command: '/unassignFromBreakout',
	},
	ReturnSelfToMainMeeting: {
		description: 'User Action: ReturnSelfToMainMeeting',
		shortDescription: 'ReturnSelfToMainMeeting',
		command: '/returnToMainMeeting',
	},
	AdmitSomeoneFromWaitingRoom: {
		description: 'User Action: AdmitSomeoneFromWaitingRoom',
		shortDescription: 'AdmitSomeoneFromWaitingRoom',
		command: '/admit',
	},
	SendSomeoneToWaitingRoom: {
		description: 'User Action: SendSomeoneToWaitingRoom',
		shortDescription: 'SendSomeoneToWaitingRoom',
		command: '/sendToWaitingRoom',
	},
	AllowWebinarAttendeeToSpeak: {
		description: 'User Action: AllowWebinarAttendeeToSpeak',
		shortDescription: 'AllowWebinarAttendeeToSpeak',
		command: '/allowToSpeak',
	},
	ShutUpWebinarAttendee: {
		description: 'User Action: ShutUpWebinarAttendee',
		shortDescription: 'ShutUpWebinarAttendee',
		command: '/disallowToSpeak',
	},

	StartScreenShare: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/startScreenshare{intscreen_id}',
	},
	StartScreenShareWithPrimaryScreen: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/startScreensharePrimary',
	},
	StartShareWithWindow: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/startWindowShare{intwindow_id}',
	},
	StartAudioShare: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/startAudioShare{intaudio_id}',
	},
	StartCameraShare: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/startCameraShare{intcamera_id}',
	},
	CycleSharedCameraToNextAvailable: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/shareNextCamera',
	},
	StopSharing: { description: 'User Action: pin', shortDescription: 'pin', command: '/stopShare' },
	RequestListWindowsForSharing: { description: 'User Action: pin', shortDescription: 'pin', command: '/listWindows' },
	RequestListScreensForSharing: { description: 'User Action: pin', shortDescription: 'pin', command: '/listScreens' },
	AllowToRecord: { description: 'User Action: pin', shortDescription: 'pin', command: '/allowToRecord' },
	DisallowToRecord: { description: 'User Action: pin', shortDescription: 'pin', command: '/disallowToRecord' },
	SetGalleryView: { description: 'User Action: pin', shortDescription: 'pin', command: '/setGalleryView' },
	GotoNextGalleryPage: { description: 'User Action: pin', shortDescription: 'pin', command: '/galleryPageNext' },
	GotoPreviousGalleryPage: { description: 'User Action: pin', shortDescription: 'pin', command: '/galleryPagePrev' },
	SetSpeakerView: { description: 'User Action: pin', shortDescription: 'pin', command: '/setSpeakerView' },
	ShowNonVideoParticipants: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/showNonVideoParticipants',
	},
	HideNonVideoParticipants: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/hideNonVideoParticipants',
	},
	ShowUserNamesOnVideo: { description: 'User Action: pin', shortDescription: 'pin', command: '/showUserNames' },
	HideUserNamesOnVideo: { description: 'User Action: pin', shortDescription: 'pin', command: '/hideUserNames' },
	EnableOriginalSound: { description: 'User Action: pin', shortDescription: 'pin', command: '/enableOriginalSound' },
	DisableOriginalSound: { description: 'User Action: pin', shortDescription: 'pin', command: '/disableOriginalSound' },
	EnableHDVideo: { description: 'User Action: pin', shortDescription: 'pin', command: '/enableHDVideo' },
	DisableHDVideo: { description: 'User Action: pin', shortDescription: 'pin', command: '/disableHDVideo' },
	EnableMirrorVideo: { description: 'User Action: pin', shortDescription: 'pin', command: '/enableMirrorVideo' },
	DisableMirrorVideo: { description: 'User Action: pin', shortDescription: 'pin', command: '/disableMirrorVideo' },
	EnableOptimizeVideoForSharing: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/enableOptimizeVideo',
	},
	DisableOptimizeVideoForSharing: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/disableOptimizeVideo',
	},
	EnableComputerSoundWhenSharing: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/enableComputerSoundWhenSharing',
	},
	DisableComputerSoundWhenSharing: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/disableComputerSoundWhenSharing',
	},
	RequestMicDeviceList: { description: 'User Action: pin', shortDescription: 'pin', command: '/listMicDevices' },
	SetMicDevice: { description: 'User Action: pin', shortDescription: 'pin', command: '/setMicDevice{intid}' },
	RequestSpeakerDeviceList: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/listSpeakerDevices',
	},
	SetSpeakerDevice: { description: 'User Action: pin', shortDescription: 'pin', command: '/setSpeakerDevice{intid}' },
	RequestMicLevel: { description: 'User Action: pin', shortDescription: 'pin', command: '/getMicLevel' },
	SetMicLevel: { description: 'User Action: pin', shortDescription: 'pin', command: '/setMicLevel{intlevel}' },
	RequestSpeakerVolume: { description: 'User Action: pin', shortDescription: 'pin', command: '/getSpeakerVolume' },
	SetSpeakerVolume: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/setSpeakerVolume{intlevel}',
	},
	RequestCameraDevices: { description: 'User Action: pin', shortDescription: 'pin', command: '/listCamerDevices' },
	SetCameraDevice: { description: 'User Action: pin', shortDescription: 'pin', command: '/setCamerDevice{intid}' },
	RequestVirtualBackgroundList: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/listBackgrounds',
	},
	SetVirtualBackground: { description: 'User Action: pin', shortDescription: 'pin', command: '/setBackground{intid}' },
	SetVideoFilter: { description: 'User Action: pin', shortDescription: 'pin', command: '/setVideoFilter{intid}' },
	RequestCurrentCameraDevice: { description: 'User Action: pin', shortDescription: 'pin', command: '/getCameraDevice' },
	RequestCurrentMicDevice: { description: 'User Action: pin', shortDescription: 'pin', command: '/getMicDevice' },
	RequestCurrentSpeakerDevice: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/getSpeakerDevice',
	},
	RequestCurrentVirtualBackground: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/getBackground',
	},
	PingZoomOSC: { description: 'User Action: pin', shortDescription: 'pin', command: '/zoom/ping' },
	SetZoomOSCSubscribeLevel: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/zoom/subscribe{intlevel}',
	},
	RequestOrderOfGalleryView: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/zoom/getGalleryOrder',
	},
	RequestOrderOfSpotlights: { description: 'User Action: pin', shortDescription: 'pin', command: '/zoom/getSpotOrder' },
	SetWindowPosition: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/setWindowPosition{intx,inty}',
	},
	SetWindowSize: { description: 'User Action: pin', shortDescription: 'pin', command: '/setWindowSize{intx,inty}' },
	PongOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/zoomosc/pong' },
	GalleryOrderOutputOutput: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/zoomosc/galleryOrder',
	},
	GalleryCountOutputOutput: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/zoomosc/galleryCount',
	},
	GalleryShapeOutputOutput: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/zoomosc/galleryShape',
	},
	TargetIDListClearedOutputOutput: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/zoomosc/listCleared',
	},
	ListOfBreakoutRoomsOutputOutput: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/zoomosc/listBreakouts',
	},
	WaitingRoomListOutputOutput: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/zoomosc/waitingRoomUserList',
	},
	AllZoomOSCParticipantDataOutputOutput: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/zoomosc/list',
	},
	ChatMessageReceivedOutputOutput: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/chat{strmsg}',
	},
	UserJoinOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/online' },
	UserLeaveOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/offline' },
	UserRoleChangedOutputOutput: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/roleChanged{introle}',
	},
	UserUnmutedOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/unmute' },
	UserMutedOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/mute' },
	UserVideoOnOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/videoOn' },
	UserVideoOffOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/videoOff' },
	ActiveSpeakerOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/activeSpeaker' },
	SpotlIghtOnOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/spotlightOn' },
	SpotlightOffOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/spotlightOff' },
	HandRaisedOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/handRaised' },
	HandLoweredOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/handLowered' },
	UserNameChangedOutputOutput: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/userNameChanged{strorig_name}',
	},
	CameraDeviceListOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/cameraDevices' },
	MicDeviceListOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/micDevices' },
	SpeakerDeviceListOutputOutput: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/speakerDevices',
	},
	VirtualBackgroundListOutputOutput: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/backgrounds',
	},
	WindowsListOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/windows' },
	ScreensListOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/screens' },
	CurrentMicOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/micDevice' },
	CurrentSpeakerOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/speakerDevice' },
	CurrentCameraOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/cameraDevice' },
	CurrentVirtualBackgroundOutputOutput: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/background',
	},
	CurrentVideoFilterOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/filter' },
	MicVolumeOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/micVolume{intvol}' },
	SpeakerVolumeOutputOutput: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/speakerVolume{intvol}',
	},
	SpotlightOrderOutputOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/spotOrder' },
	UserEmojiChangedOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/emojiChanged' },
	UserIsSpeakingOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/isSpeaking' },
	UserStoppedSpeakingOutput: { description: 'User Action: pin', shortDescription: 'pin', command: '/stoppedSpeaking' },
	UserAskedWebinarQuestionOutput: {
		description: 'User Action: pin',
		shortDescription: 'pin',
		command: '/askedQuestion{strquestion}',
	},
}
const GlobalActions = {
	MuteAll: { description: 'User Action: MuteAll', shortDescription: 'MuteAll', command: '/zoom/all/mute' },
	UnmuteAll: { description: 'Global Action: UnmuteAll', shortDescription: 'UnmuteAll', command: '/zoom/all/unMute' },
	ClearSpotlight: {
		description: 'Global Action: ClearSpotlight',
		shortDescription: 'ClearSpotlight',
		command: '/zoom/clearSpot',
	},
	EnableUsersToUnmute: {
		description: 'Global Action: EnableUsersToUnmute',
		shortDescription: 'EnableUsersToUnmute',
		command: '/zoom/enableUserUnmute',
	},
	DisableUsersToUnmute: {
		description: 'Global Action: DisableUsersToUnmute',
		shortDescription: 'DisableUsersToUnmute',
		command: '/zoom/disableUserUnmute',
	},
	SendAChatToEveryone: {
		description: 'Global Action: SendAChatToEveryone',
		shortDescription: 'SendAChatToEveryone',
		command: '/zoom/chatAll',
		args: ['msg'],
	},
	LowerAllHands: {
		description: 'Global Action: LowerAllHands',
		shortDescription: 'LowerAllHands',
		command: '/zoom/lowerAllHands',
	},
	RequestBreakoutList: {
		description: 'Global Action: RequestBreakoutList',
		shortDescription: 'RequestBreakoutList',
		command: '/zoom/listBreakouts',
	},
	CreateBreakoutRoom: {
		description: 'Global Action: CreateBreakoutRoom',
		shortDescription: 'CreateBreakoutRoom',
		command: '/zoom/createBreakout{strname}',
	},
	DeleteBreakoutRoom: {
		description: 'Global Action: DeleteBreakoutRoom',
		shortDescription: 'DeleteBreakoutRoom',
		command: '/zoom/deleteBreakout{strname|intbo_index}',
	},
	OpenBreakoutRooms: {
		description: 'Global Action: OpenBreakoutRooms',
		shortDescription: 'OpenBreakoutRooms',
		command: '/zoom/openBreakouts',
	},
	CloseBreakoutRooms: {
		description: 'Global Action: CloseBreakoutRooms',
		shortDescription: 'CloseBreakoutRooms',
		command: '/zoom/closeBreakouts',
	},
	ConfigureBreakoutRooms: {
		description: 'Global Action: ConfigureBreakoutRooms',
		shortDescription: 'ConfigureBreakoutRooms',
		command:
			'/zoom/configureBreakouts{intpostCloseSeconds,intallowChooseBreakout(0=false,1=true),intallowReturnAtWill,intautoMoveParticipants,intuseTimer,intcloseWithTimer,intbreakoutDurrationSeconds}',
	},
	DeleteAllBreakoutRooms: {
		description: 'Global Action: DeleteAllBreakoutRooms',
		shortDescription: 'DeleteAllBreakoutRooms',
		command: '/zoom/deleteAllBreakouts',
	},
	BroadcastMessageToBreakoutRooms: {
		description: 'Global Action: BroadcastMessageToBreakoutRooms',
		shortDescription: 'BroadcastMessageToBreakoutRooms',
		command: '/zoom/broadcastToBreakouts{strmsg}',
	},
	AdmitEveryoneFromWaitingRoom: {
		description: 'Global Action: AdmitEveryoneFromWaitingRoom',
		shortDescription: 'AdmitEveryoneFromWaitingRoom',
		command: '/zoom/admitAll',
	},
	SendMessageToWaitingRoom: {
		description: 'Global Action: SendMessageToWaitingRoom',
		shortDescription: 'SendMessageToWaitingRoom',
		command: '/zoom/messageWaitingRoom{strmsg}',
	},
	EjectAllWebinarAttendees: {
		description: 'Global Action: EjectAllWebinarAttendees',
		shortDescription: 'EjectAllWebinarAttendees',
		command: '/zoom/ejectAttendees',
	},
	StartLocalRecording: {
		description: 'Global Action: StartLocalRecording',
		shortDescription: 'StartLocalRecording',
		command: '/zoom/startLocalRecording',
	},
	PauseLocalRecording: {
		description: 'Global Action: PauseLocalRecording',
		shortDescription: 'PauseLocalRecording',
		command: '/zoom/pauseLocalRecording',
	},
	ResumeLocalRecording: {
		description: 'Global Action: ResumeLocalRecording',
		shortDescription: 'ResumeLocalRecording',
		command: '/zoom/resumeLocalRecording',
	},
	StopLocalRecording: {
		description: 'Global Action: StopLocalRecording',
		shortDescription: 'StopLocalRecording',
		command: '/zoom/stopLocalRecording',
	},
	StartCloudRecording: {
		description: 'Global Action: StartCloudRecording',
		shortDescription: 'StartCloudRecording',
		command: '/zoom/startCloudRecording',
	},
	PauseCloudRecording: {
		description: 'Global Action: PauseCloudRecording',
		shortDescription: 'PauseCloudRecording',
		command: '/zoom/pauseCloudRecording',
	},
	ResumeCloudRecording: {
		description: 'Global Action: ResumeCloudRecording',
		shortDescription: 'ResumeCloudRecording',
		command: '/zoom/resumeCloudRecording',
	},
	StopCloudRecording: {
		description: 'Global Action: StopCloudRecording',
		shortDescription: 'StopCloudRecording',
		command: '/zoom/stopCloudRecording',
	},
	UpdateTargetIDs: {
		description: 'Global Action: UpdateTargetIDs',
		shortDescription: 'UpdateTargetIDs',
		command: '/zoom/update',
	},
	AppendTargetIDs: {
		description: 'Global Action: AppendTargetIDs',
		shortDescription: 'AppendTargetIDs',
		command: '/zoom/include',
	},
	SetZoomOSCGalleryTrackingMode: {
		description: 'Global Action: SetZoomOSCGalleryTrackingMode',
		shortDescription: 'SetZoomOSCGalleryTrackingMode',
		command: '/zoom/galTrackMode{intmode}',
	},
	RequestGalleryCount: {
		description: 'Global Action: RequestGalleryCount',
		shortDescription: 'RequestGalleryCount',
		command: '/zoom/galCount',
	},
	LoadTargetIDs: {
		description: 'Global Action: LoadTargetIDs',
		shortDescription: 'LoadTargetIDs',
		command: '/zoom/load',
	},
	SaveTargetIDs: {
		description: 'Global Action: SaveTargetIDs',
		shortDescription: 'SaveTargetIDs',
		command: '/zoom/save',
	},
	RequestAllZoomOSCParticipantDataList: {
		description: 'Global Action: RequestAllZoomOSCParticipantDataList',
		shortDescription: 'RequestAllZoomOSCParticipantDataList',
		command: '/zoom/listBreakouts',
	},
	ResetTargetIDs: {
		description: 'Global Action: ResetTargetIDs',
		shortDescription: 'ResetTargetIDs',
		command: '/zoom/reset',
	},
	LeaveMeeting: {
		description: 'Global Action: LeaveMeeting',
		shortDescription: 'LeaveMeeting',
		command: '/zoom/leaveMeeting',
	},
	EndMeeting: { description: 'Global Action: EndMeeting', shortDescription: 'EndMeeting', command: '/zoom/endMeeting' },
	EnableWaitingRoom: {
		description: 'Global Action: EnableWaitingRoom',
		shortDescription: 'EnableWaitingRoom',
		command: '/zoom/enableWaitingRoom',
	},
	DisableWaitingRoom: {
		description: 'Global Action: DisableWaitingRoom',
		shortDescription: 'DisableWaitingRoom',
		command: '/zoom/disableWaitingRoom',
	},
	JoinMeeting: {
		description: 'Global Action: JoinMeeting',
		shortDescription: 'JoinMeeting',
		command: '/zoom/joinMeeting{strmeetingID,stringname,stringpw(optional)}',
	},
	ZAKJoinMeeting: {
		description: 'Global Action: ZAKJoinMeeting',
		shortDescription: 'ZAKJoinMeeting',
		command: '/zoom/zakJoin{strzak,strmeetingID,strname}',
	},
	ZAKStartMeeting: {
		description: 'Global Action: ZAKStartMeeting',
		shortDescription: 'ZAKStartMeeting',
		command: '/zoom/zakStart{strzak,strmeetingID,strname}',
	},
}

if (module != undefined) module.exports = { UserActions, GlobalActions }
